name: Publish 🚀

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: CiCdAzureWebApiTest
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  PROJECT_FOLDER: ./CiCdAzureWebApi
  TARGET_FRAMEWORK: net8.0
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./CiCdAzureWebApi.sln
    - name: Build
      run: dotnet build ./CiCdAzureWebApi.sln --no-restore
    - name: Test
      run: dotnet test ./CiCdAzureWebApi.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./CiCdAzureWebApi.sln --configuration Release --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.CICDAZUREDEPLOYTEST }}
        package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
